### ISSUE TITLE
error: expected ident, found `"static"`

### ISSUE THREAD

**Issue by buster** [iron/staticfile#32]
In the current nightly this does not work... Is there a way to make it work?

**Comment by buster** [comment]
Sorry, so the complete error is:

```
src/main.rs:4:14: 4:22 error: expected ident, found `"static"`
src/main.rs:4 extern crate "static" as static_file;
```

**Comment by gsingh93** [comment]
`extern crate "static" as static_file;` is no longer valid Rust, quotes are no longer allowed. However, since `static` is a keyword, you can't use it without the quotes either. The name of the library will have to be changed.

**Comment by reem** [comment]
Changed to `staticfile`.
