### ISSUE TITLE
HttpDate change in Hyper

### ISSUE THREAD

**Issue by tsurai** [iron/staticfile#33]
Hyper has added a wrapper around time::Tm called HttpDate causing compile error in static_handler.rs because its trying to use time::Tm directly.

I wanted to fix the problem and open a pull requests but refrained from doing so when I noticed that Iron reexports parts of hyper instead of using hyper as a direct dependency for static. I don't know how you would prefer to get HttpDate from hyper into static.

**Comment by reem** [comment]
Iron reexports hyper's header module as `iron::headers`, so you should be able to find everything there.

If you find that you need a type from hyper that isn't re-exported, I consider that a bug in Iron - it should be usable standalone.

**Comment by reem** [comment]
Fixed in master.
