### ISSUE TITLE
Compression support

### ISSUE THREAD

**Issue by gsquire** [iron/staticfile#40]
Would you be interested in adding compression for this library or somewhere else in the Iron framework?

**Comment by reem** [comment]
Compression is an ideal candidate for an AfterMiddleware, probably in another package. I can create iron/compress a bit later if you want to work on it?

**Comment by gsquire** [comment]
Sounds good to me. I can study up on the workings of the AfterMiddleware some more and then go from there once it is up.

**Comment by reem** [comment]
@gsquire created iron/compress, feel free to open issues/PRs there.
