### ISSUE TITLE
how to use staticfile with router?

### ISSUE THREAD

**Issue by ilkosta** [iron/staticfile#50]
Hi,

I've tried to associate the Static handler to a the `get` of a route and a chain to the `post` as:

```rust
router.get("/odt2pdf", staticfile::Static::new(Path::new("src/asset/html/")));
router.post("/odt2pdf", logger::get_log_enabled_handler(Box::new(chain_form_file)));
```

The goal is to make available a sample form to test a simple REST webservice.

The POST method work correctly, but the GET isn't working:

```shell
curl -v "http://localhost:3000/odt2pdf"
*   Trying ::1...
* Connected to localhost (::1) port 3000 (#0)
> GET /odt2pdf HTTP/1.1
> Host: localhost:3000
> User-Agent: curl/7.44.0
> Accept: */*
> 
< HTTP/1.1 404 Not Found
< Content-Length: 0
< Date: Tue, 18 Aug 2015 10:12:51 GMT
< 
* Connection #0 to host localhost left intact
```

what is it that I'm missing?

**Comment by ilkosta** [comment]
the toy project where I'm trying to use router+staticfile is https://github.com/ilkosta/odt2pdf

**Comment by panicbit** [comment]
@ilkosta I guess the files you are trying to serve are not in "./odt2pdf/src/asset/html/" ? Because that's what's happening.
If you want to strip the "odt2pdf" path you can use [mount](https://github.com/iron/mount).

**Comment by reem** [comment]
Yeah, you need to use Mount to strip the `odtp2pdf` from the url for the internal handlers, router will just route those exact routes.
