### ISSUE TITLE
Staticfile treats all requests as GET.

### ISSUE THREAD

**Issue by ehiggs** [iron/staticfile#54]
Staticfile treats all requests as GET. E.g. HEAD should just return metadata but instead returns the whole file.

This was originally iron/mount#75

**Comment by reem** [comment]
Definitely. It would also be great if we did things like respond correctly to the `Range` header and other such niceties.

**Comment by ehiggs** [comment]
Was this fixed by #57? If so, let's close it. Thanks!

**Comment by untitaker** [comment]
The performance problem specifically mentioned in the OP was fixed, but IMO it should also return a errorcode if something other than `{GET, HEAD}` is used.

**Comment by ehiggs** [comment]
>IMO it should also return a errorcode if something other than {GET, HEAD} is used.

Sure, so if the request is not in `{GET, HEAD, PUT, POST, DELETE, TRACE, CONNECT, PATCH}` then it should return `400 BAD REQUEST`. If the request is not in `{GET, HEAD}` then iron can return `405 METHOD NOT ALLOWED`. Separate ticket, surely.
