### ISSUE TITLE
Cannot request a file with a space in the name

### ISSUE THREAD

**Issue by franza** [iron/staticfile#60]
Assume you have a file `~/mount_dir/file with spaces.txt`. Then you request it using `staticfile` with URL like `http://localhost:3000/mount_dir/file%20with%20spaces.txt`. The `%20` characters are not decoded inside of the library so it will return 404.

**Comment by franza** [comment]
I would like to contribute with a fix but building project fails with

```
native library `openssl` is being linked to by more than one package, and can only be linked to by one package

  openssl-sys v0.7.1
  openssl-sys v0.6.7
```

I'm quite new to Rust so I'll appreciate if someone assists me with that.

**Comment by franza** [comment]
Looks like I was able to fix that after I set `hyper = "0.7"` in `Cargo.toml`.

**Comment by Dashed** [comment]
:+1: Can confirm this bug.

**Comment by reem** [comment]
Should be fixed on master, soon on crates.io.

**Comment by Dashed** [comment]
Slick. Thanks @reem  :+1:

**Comment by franza** [comment]
Cool, thanks!
