### ISSUE TITLE
Caching will rarely work on systems that have nanosecond-precision filetimes 

### ISSUE THREAD

**Issue by shepmaster** [iron/staticfile#75]
Debugging why my caching wasn't caching, I printed out these values:

```rust
Timespec { sec: 1467045092, nsec: 368456132 } // last_modified_time
Timespec { sec: 1467045092, nsec: 0 }         // if_modified_since
```

Looking at [the code](https://github.com/iron/staticfile/blob/52265d5bada83a7bb770c0250c1286dc674e4ed8/src/static_handler.rs#L165-L166):

```rust
let time = FileTime::from_last_modification_time(&metadata);
Timespec::new(time.seconds() as i64, time.nanoseconds() as i32)
```

But the HTTP header will never have nanosecond precision (`If-Modified-Since:Mon, 27 Jun 2016 16:31:32 GMT`), so the comparison will fail unless the nanosecond field *happens* to be zero.

My local fix is to change the code to 

```rust
Timespec::new(time.seconds() as i64, 0)
```

Does that feel like the right solution? I'd be happy to submit a PR to that end.

**Comment by TheNeikos** [comment]
That seems correct by the spec: https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.25

**Comment by shepmaster** [comment]
> That seems correct by the spec
@TheNeikos could you clarify what "that" is in your sentence? You could mean "caching should rarely work" is correct, or "ignoring nanoseconds" is correct.

**Comment by untitaker** [comment]
We could switch to ETags to preserve nanosecond precision. However, your fix is correct (I assume there is no way to represent nanoseconds in HTTP dates).

**Comment by TheNeikos** [comment]
> @TheNeikos could you clarify what "that" is in your sentence? You could mean "caching should rarely work" is correct, or "ignoring nanoseconds" is correct.

The latter of course

**Comment by Hoverbear** [comment]
@shepmaster That change LGTM please feel free to make a PR. I'll merge it when the tests pass. :)

**Comment by shepmaster** [comment]
@Hoverbear uhh, didn't [you already merge it](https://github.com/iron/staticfile/pull/82)? My bad for not linking to the issue though!

**Comment by Hoverbear** [comment]
LOL. You're right!
